server {
    listen 8080;
    server_name localhost;
    client_max_body_size 10485760;

    error_page 404 /www/error_pages/404.html;
    error_page 403 /www/error_pages/403.html;
    error_page 500 /www/error_pages/500.html;

    cgi .py /usr/bin/python3;
    cgi .php /usr/local/bin/php-cgi;


    location / {
        allow_methods GET POST;
        root www/first;
        index index.html;
    }

    location /upload/ {
        allow_methods GET POST DELETE;
        root www/first/upload;
        client_max_body_size 100;
        autoindex on;
        upload_enable on;
        upload_store www/first/upload;
    }

    location /methods/ {
        allow_methods GET;
        root www/first;
        index index.html;
        autoindex off;
    }

    location /listing/ {
        allow_methods GET;
        root www/first;
        autoindex on;
    }

    location /old-site/ {
        allow_methods GET;
        root    www;
        return 302 http://127.0.0.1:8080/new-site/index.html;
    }

    location /new-site/ {
        allow_methods GET;
        root    www/new-site;
    }

    location /cgi-bin/ {
        allow_methods GET POST;
        root www/cgi-bin;
    }

    # location /directory/ {
    #     allow_methods GET;
    #     root YoupiBanane;
    #     index youpi.bad_extension;
    # }
}

server {
    listen localhost:8081;

    server_name local.dev;

    location / {
        allow_methods GET;
        root www/second;
        index second.html;
    }
}
